apiVersion: apps/v1
kind: Deployment
metadata:
  name: kam-dashboard # {"$openapi":"DASHBOARD_NAME"}
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: kam-dashboard # {"$openapi":"DASHBOARD_NAME"}
  template:
    metadata:
      labels:
        deployment: kam-dashboard # {"$openapi":"DASHBOARD_NAME"}
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
    spec:
      serviceAccount: kam-dashboard # {"$openapi":"DASHBOARD_NAME"}
      containers:
      - name: kam-dashboard # {"$openapi":"DASHBOARD_NAME"}
        image: s2i-odh-dashboard:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 300Mi
          limits:
            cpu: 500m
            memory: 1000Mi
        livenessProbe:
          httpGet:
            path: /api/status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 15
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 15
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
