apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: kam-dashboard # {"$openapi":"DASHBOARD_NAME"}
  app.kubernetes.io/part-of: kam-dashboard # {"$openapi":"DASHBOARD_NAME"}
resources:
#- application.yaml
- role.yaml
- cluster-role.yaml
- service-account.yaml
- role-binding.yaml
- cluster-role-binding.yaml
- deployment.yaml
- routes.yaml
- service.yaml
